### ISSUE TITLE
copy text from google breaks clipster with python2 

### ISSUE THREAD

**Issue by magnetophon** [mrichar1/clipster#32]
Thanks for making clipster! 

When I copy a text from google search results, ``clipster -d -l DEBUG`` goes into an endless loop, presumably because of https://github.com/mrichar1/clipster/issues/1.
When I build clipster with python3, all is fine.

**Comment by mrichar1** [comment]
Hi - thanks for reporting this bug. I've just had a quick test of this and I can't seem to replicate the issue.

Can you provide the following:
1. Name and version of the browser you're using.
2. Exact steps to make the search and select in google.
3. The DEBUG messages (at least one loop's worth) from clipster.

Thanks!

**Comment by magnetophon** [comment]
I've tried to work out a minimal case, but I'm sorry to say I haven't found exactly how to trigger it.
This is the closest I've gotten:

1) Firefox 49.0 on NixOS, with a fresh new profile.
2a) go to google.com 
 b) search ``clipster``
 c) select some text with the mouse. clipster is fine
 d) again select some text with the mouse. clipster goes wild.
3) http://pastebin.com/Nxg4dyCt

**Comment by mrichar1** [comment]
Thanks for this - line 35 of the full logs provided the clue to (yet another instance) where unicode wasn't handled properly for 2.x:

```/nix/store/gd2ryjxc1vycsvgwfn0nrac9f4rn5a3m-clipster-unstable-2016-12-08/bin/.clipster-wrapped:424: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
 if self.read_board(boards[0]) != text:
```

This should now be fixed in 9848f0645eaa9042c9f4a329faf74b1c242ad087.

Please grab the latest version of clipster and let me know if this fixes the bug for you.

Thanks!

**Comment by magnetophon** [comment]
Thanks, that fixes it.
I still get an empty rofi menu sometimes, but I'll open a new issue when I have a bit more concrete information.
